"""create session

Revision ID: 42a342630d34
Revises: d90a21c629e4
Create Date: 2026-08-12 23:26:18.650236
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '42a342630d34'
down_revision: str | None = 'd90a21c629e4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_session_user_id_user_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session'))
    )
    op.create_index(op.f('ix_session_expires_at'), 'session', ['expires_at'], unique=False)
    op.create_index(op.f('ix_session_token_hash'), 'session', ['token_hash'], unique=True)
    op.create_index(op.f('ix_session_user_id'), 'session', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_user_id'), table_name='session')
    op.drop_index(op.f('ix_session_token_hash'), table_name='session')
    op.drop_index(op.f('ix_session_expires_at'), table_name='session')
    op.drop_table('session')
    # ### end Alembic commands ###
