"""competitions

Revision ID: 12213205a069
Revises: f5e4a17124dc
Create Date: 2026-08-17 19:32:01.879427
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '12213205a069'
down_revision: str | None = 'f5e4a17124dc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competition',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('prize', sa.String(length=200), nullable=True),
    sa.Column('metric_definition_id', sa.BigInteger(), nullable=False),
    sa.Column('entity_type', sa.String(length=8), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('settlement_hours', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tie_break', sa.String(length=24), nullable=False),
    sa.Column('min_participation', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("entity_type IN ('user', 'team')", name=op.f('ck_competition_entity_type_valid')),
    sa.CheckConstraint("state IN ('draft', 'scheduled', 'active', 'ended', 'closed', 'cancelled')", name=op.f('ck_competition_state_valid')),
    sa.CheckConstraint("tie_break IN ('earliest_to_reach', 'shared_rank')", name=op.f('ck_competition_tie_break_valid')),
    sa.CheckConstraint('ends_at > starts_at', name=op.f('ck_competition_window_ordered')),
    sa.CheckConstraint('settlement_hours BETWEEN 0 AND 168', name=op.f('ck_competition_settlement_sane')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user_account.id'], name=op.f('fk_competition_created_by_user_id_user_account'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['metric_definition_id'], ['metric_definition.id'], name=op.f('fk_competition_metric_definition_id_metric_definition'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_competition_organization_id_organization'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_competition'))
    )
    op.create_index('ix_competition_org_state', 'competition', ['organization_id', 'state'], unique=False)
    op.create_table('competition_participant',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('competition_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('team_id', sa.BigInteger(), nullable=True),
    sa.Column('final_rank', sa.Integer(), nullable=True),
    sa.Column('final_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('reached_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(user_id IS NOT NULL AND team_id IS NULL) OR (user_id IS NULL AND team_id IS NOT NULL)', name=op.f('ck_competition_participant_one_subject')),
    sa.ForeignKeyConstraint(['competition_id'], ['competition.id'], name=op.f('fk_competition_participant_competition_id_competition'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name=op.f('fk_competition_participant_team_id_team'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_competition_participant_user_id_user_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_competition_participant'))
    )
    op.create_index('ix_competition_participant_comp', 'competition_participant', ['competition_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_competition_participant_comp', table_name='competition_participant')
    op.drop_table('competition_participant')
    op.drop_index('ix_competition_org_state', table_name='competition')
    op.drop_table('competition')
    # ### end Alembic commands ###
