"""notification celebrated_at

Revision ID: 8e5c0c623afc
Revises: 04e7756358d3
Create Date: 2026-08-14 21:41:59.364197
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '8e5c0c623afc'
down_revision: str | None = '04e7756358d3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('celebrated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'celebrated_at')
    # ### end Alembic commands ###
