"""create office

Revision ID: 8121b4557463
Revises: dbca172c95c7
Create Date: 2026-08-13 19:41:21.498242
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '8121b4557463'
down_revision: str | None = 'dbca172c95c7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('office',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_office_organization_id_organization')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_office'))
    )
    op.create_index(op.f('ix_office_organization_id'), 'office', ['organization_id'], unique=False)
    op.add_column('team', sa.Column('office_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_team_office_id'), 'team', ['office_id'], unique=False)
    op.create_foreign_key(op.f('fk_team_office_id_office'), 'team', 'office', ['office_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_team_office_id_office'), 'team', type_='foreignkey')
    op.drop_index(op.f('ix_team_office_id'), table_name='team')
    op.drop_column('team', 'office_id')
    op.drop_index(op.f('ix_office_organization_id'), table_name='office')
    op.drop_table('office')
    # ### end Alembic commands ###
