"""add leaderboard

Revision ID: 03e6d763bb91
Revises: 94dbf79bfd70
Create Date: 2026-08-14 15:22:28.293179
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '03e6d763bb91'
down_revision: str | None = '94dbf79bfd70'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leaderboard',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('metric_definition_id', sa.BigInteger(), nullable=False),
    sa.Column('entity_type', sa.String(length=8), server_default='user', nullable=False),
    sa.Column('scope_type', sa.String(length=16), server_default='organization', nullable=False),
    sa.Column('scope_team_id', sa.BigInteger(), nullable=True),
    sa.Column('period_type', sa.String(length=16), server_default='month', nullable=False),
    sa.Column('display_limit', sa.Integer(), nullable=True),
    sa.Column('visibility', sa.String(length=8), server_default='org', nullable=False),
    sa.Column('is_tv_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('rank_method', sa.String(length=16), server_default='rank', nullable=False),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(scope_type = 'team' AND scope_team_id IS NOT NULL) OR (scope_type = 'organization' AND scope_team_id IS NULL)", name=op.f('ck_leaderboard_scope_matches_type')),
    sa.CheckConstraint("entity_type IN ('user', 'team')", name=op.f('ck_leaderboard_entity_type_valid')),
    sa.CheckConstraint("period_type IN ('day', 'week', 'month', 'quarter', 'year', 'rolling_7', 'rolling_30')", name=op.f('ck_leaderboard_period_type_valid')),
    sa.CheckConstraint("rank_method IN ('rank', 'dense_rank')", name=op.f('ck_leaderboard_rank_method_valid')),
    sa.CheckConstraint("scope_type IN ('organization', 'team')", name=op.f('ck_leaderboard_scope_type_valid')),
    sa.CheckConstraint("visibility <> 'team' OR scope_type = 'team'", name=op.f('ck_leaderboard_team_visibility_needs_a_team')),
    sa.CheckConstraint("visibility IN ('org', 'team', 'private')", name=op.f('ck_leaderboard_visibility_valid')),
    sa.CheckConstraint('display_limit IS NULL OR display_limit > 0', name=op.f('ck_leaderboard_display_limit_positive')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user_account.id'], name=op.f('fk_leaderboard_created_by_user_id_user_account'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['metric_definition_id'], ['metric_definition.id'], name=op.f('fk_leaderboard_metric_definition_id_metric_definition')),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_leaderboard_organization_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scope_team_id'], ['team.id'], name=op.f('fk_leaderboard_scope_team_id_team'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leaderboard'))
    )
    op.create_index('ix_leaderboard_org', 'leaderboard', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_leaderboard_org', table_name='leaderboard')
    op.drop_table('leaderboard')
    # ### end Alembic commands ###
