"""add display

Revision ID: 1e2bfaae4daa
Revises: 3d61902cb44e
Create Date: 2026-08-14 17:17:54.260427
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '1e2bfaae4daa'
down_revision: str | None = '3d61902cb44e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('display',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('office_id', sa.BigInteger(), nullable=True),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user_account.id'], name=op.f('fk_display_created_by_user_id_user_account'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['office_id'], ['office.id'], name=op.f('fk_display_office_id_office'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_display_organization_id_organization'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_display'))
    )
    op.create_index(op.f('ix_display_organization_id'), 'display', ['organization_id'], unique=False)
    op.create_index(op.f('ix_display_token_hash'), 'display', ['token_hash'], unique=True)
    op.create_check_constraint(op.f('ck_leaderboard_tv_requires_org_visibility'), 'leaderboard', "is_tv_enabled = false OR visibility = 'org'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_leaderboard_tv_requires_org_visibility'), 'leaderboard', type_='check')
    op.drop_index(op.f('ix_display_token_hash'), table_name='display')
    op.drop_index(op.f('ix_display_organization_id'), table_name='display')
    op.drop_table('display')
    # ### end Alembic commands ###
