"""create sso_config

Revision ID: 26c2c84a32ab
Revises: ea979e4d0d6f
Create Date: 2026-08-13 17:57:26.366098
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '26c2c84a32ab'
down_revision: str | None = 'ea979e4d0d6f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sso_config',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('issuer', sa.String(length=500), nullable=True),
    sa.Column('client_id', sa.String(length=500), nullable=True),
    sa.Column('client_secret_encrypted', sa.String(length=2000), nullable=True),
    sa.Column('scopes', sa.String(length=500), server_default='openid profile email', nullable=False),
    sa.Column('button_label', sa.String(length=100), server_default='Sign in with SSO', nullable=False),
    sa.Column('auto_provision', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('require_sso', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_sso_config_organization_id_organization')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sso_config')),
    sa.UniqueConstraint('organization_id', name=op.f('uq_sso_config_organization_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sso_config')
    # ### end Alembic commands ###
