"""channel ip allowlist

Revision ID: f5e4a17124dc
Revises: 3436beb94a7e
Create Date: 2026-08-17 19:10:50.402677
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'f5e4a17124dc'
down_revision: str | None = '3436beb94a7e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel', sa.Column('allowed_ips', postgresql.ARRAY(sa.String(length=64)), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channel', 'allowed_ips')
    # ### end Alembic commands ###
