"""add audit_log

Revision ID: d7abd64d8a2c
Revises: 8121b4557463
Create Date: 2026-08-13 19:58:09.275335
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'd7abd64d8a2c'
down_revision: str | None = '8121b4557463'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('actor_user_id', sa.BigInteger(), nullable=True),
    sa.Column('actor_email', sa.String(length=320), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_user_id', sa.BigInteger(), nullable=True),
    sa.Column('target_email', sa.String(length=320), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['user_account.id'], name=op.f('fk_audit_log_actor_user_id_user_account'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_audit_log_organization_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_user_id'], ['user_account.id'], name=op.f('fk_audit_log_target_user_id_user_account'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index('ix_audit_log_org_time', 'audit_log', ['organization_id', 'occurred_at'], unique=False)
    op.create_index('ix_audit_log_target_time', 'audit_log', ['target_user_id', 'occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_log_target_time', table_name='audit_log')
    op.drop_index('ix_audit_log_org_time', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
