"""channels are not archived

Teams, offices and goals keep their archive; channels lose theirs.

Those three earn it. `metric_fact` points at a team and an office with
ON DELETE NO ACTION, so Postgres *refuses* to delete one that has any history —
archiving is the only way to retire it. And an archived goal is how "we hit 4
of 5 last quarter" stays answerable.

A channel is pure configuration. Nothing historical references one: no fact, no
notification, no export. An archived state bought a tab, two endpoints and a
third case for every list to reason about, in exchange for nothing.

**This is destructive and does not round-trip.** The downgrade adds the column
back, but nothing can repopulate it — an archived channel becomes an ordinary
one. Safe here because there were none; worth saying out loud rather than
letting somebody assume otherwise from the presence of a downgrade.

Revision ID: 991102e576a5
Revises: c8860eaaa3c9
Create Date: 2026-08-17 17:45:28.465591
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '991102e576a5'
down_revision: str | None = 'c8860eaaa3c9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channel', 'archived_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel', sa.Column('archived_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
