"""notification preference

Revision ID: 04e7756358d3
Revises: cb0dbe4413c0
Create Date: 2026-08-14 21:28:00.861327
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '04e7756358d3'
down_revision: str | None = 'cb0dbe4413c0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_preference',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('event_key', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_notification_preference_user_id_user_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'event_key', name=op.f('pk_notification_preference'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_preference')
    # ### end Alembic commands ###
