"""notification

Two things in here are load-bearing and easy to lose in a later edit.

**`uq_notification_once` is what makes "announce once" work**, and it replaces
the stored "last notified status" the original design implied. The detection
job inserts with ON CONFLICT DO NOTHING, so a second announcement is impossible
rather than merely unlikely — the same reasoning as the partial unique index
that stops recurring goals spawning twice.

**`NULLS NOT DISTINCT` is not decoration.** Postgres treats NULLs as distinct in
a unique index by default, so without it every event with no period — a
competition starting, say — would insert again on every job cycle, forever. The
default is the wrong one for this table.

The index is also PARTIAL on `created_by_user_id IS NULL`, so only *detected*
events latch. An authored shout-out must be repeatable: two good weeks are two
shout-outs, and a manager praising the same person twice is the feature working
rather than a duplicate.

Revision ID: cb0dbe4413c0
Revises: 9b47c2e05a13
Create Date: 2026-08-14 21:01:32.468143
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'cb0dbe4413c0'
down_revision: str | None = '9b47c2e05a13'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('event_key', sa.String(length=64), nullable=False),
    sa.Column('subject_type', sa.String(length=32), nullable=False),
    sa.Column('subject_id', sa.BigInteger(), nullable=False),
    sa.Column('period_anchor', sa.Date(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=True),
    sa.Column('link_url', sa.String(length=200), nullable=True),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user_account.id'], name=op.f('fk_notification_created_by_user_id_user_account'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_notification_organization_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_notification_user_id_user_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification'))
    )
    op.create_index('ix_notification_feed', 'notification', ['organization_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_notification_organization_id'), 'notification', ['organization_id'], unique=False)
    op.create_index('ix_notification_unread', 'notification', ['user_id', 'created_at'], unique=False, postgresql_where='read_at IS NULL')
    op.create_index('uq_notification_once', 'notification', ['organization_id', 'user_id', 'subject_type', 'subject_id', 'period_anchor', 'event_key'], unique=True, postgresql_nulls_not_distinct=True, postgresql_where='created_by_user_id IS NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_notification_once', table_name='notification', postgresql_nulls_not_distinct=True, postgresql_where='created_by_user_id IS NULL')
    op.drop_index('ix_notification_unread', table_name='notification', postgresql_where='read_at IS NULL')
    op.drop_index(op.f('ix_notification_organization_id'), table_name='notification')
    op.drop_index('ix_notification_feed', table_name='notification')
    op.drop_table('notification')
    # ### end Alembic commands ###
