"""notification about

Adds "who this is about", which is not the same as who it is addressed to: a
team goal being hit sends a row to every member, and a feed keyed on the
recipient would list one achievement four times under four names, none of them
the achiever.

**The backfill is the point of writing this by hand.** These columns are
populated at emit, and emitting is idempotent — the unique index means the
detection job will never revisit a notification it has already written. So
without a backfill, every notification that existed before this migration keeps
a NULL name *forever*, and the achievements feed renders them nameless.

Found on the dev data rather than reasoned out: after adding the columns, a
re-run reported "0 emitted, 32 already known" and the feed came back with
blanks.

Revision ID: 81b04ef02dcf
Revises: 8e5c0c623afc
Create Date: 2026-08-14 21:51:19.269152
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '81b04ef02dcf'
down_revision: str | None = '8e5c0c623afc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('about_name', sa.String(length=120), nullable=True))
    op.add_column('notification', sa.Column('about_user_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(op.f('fk_notification_about_user_id_user_account'), 'notification', 'user_account', ['about_user_id'], ['id'], ondelete='SET NULL')
    # Backfill, in the same two shapes the emitter uses.
    #
    # A goal notification is about the goal's subject, resolved through the
    # goal rather than from the notification, which only knows the goal id.
    op.execute(
        """
        UPDATE notification n
           SET about_name = COALESCE(u.full_name, t.name),
               about_user_id = u.id
          FROM goal g
          LEFT JOIN user_account u ON u.id = g.subject_user_id
          LEFT JOIN team t ON t.id = g.subject_team_id
         WHERE n.subject_type = 'goal'
           AND n.subject_id = g.id
        """
    )
    # A shout-out is about the person it names, which is its own subject.
    op.execute(
        """
        UPDATE notification n
           SET about_name = u.full_name,
               about_user_id = u.id
          FROM user_account u
         WHERE n.subject_type = 'user'
           AND n.subject_id = u.id
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_notification_about_user_id_user_account'), 'notification', type_='foreignkey')
    op.drop_column('notification', 'about_user_id')
    op.drop_column('notification', 'about_name')
    # ### end Alembic commands ###
