"""add metric_fact

Revision ID: e5f0d64f428c
Revises: 05c9b30d5444
Create Date: 2026-08-13 20:53:13.947820
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'e5f0d64f428c'
down_revision: str | None = '05c9b30d5444'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metric_fact',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('metric_definition_id', sa.BigInteger(), nullable=False),
    sa.Column('subject_user_id', sa.BigInteger(), nullable=False),
    sa.Column('subject_team_id', sa.BigInteger(), nullable=True),
    sa.Column('value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_type', sa.String(length=16), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source_type IN ('manual', 'import', 'connector')", name=op.f('ck_metric_fact_source_type_valid')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user_account.id'], name=op.f('fk_metric_fact_created_by_user_id_user_account'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['metric_definition_id'], ['metric_definition.id'], name=op.f('fk_metric_fact_metric_definition_id_metric_definition')),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_metric_fact_organization_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_team_id'], ['team.id'], name=op.f('fk_metric_fact_subject_team_id_team')),
    sa.ForeignKeyConstraint(['subject_user_id'], ['user_account.id'], name=op.f('fk_metric_fact_subject_user_id_user_account')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metric_fact'))
    )
    op.create_index('ix_metric_fact_leaderboard', 'metric_fact', ['organization_id', 'metric_definition_id', 'occurred_at', 'subject_user_id'], unique=False)
    op.create_index('ix_metric_fact_subject_time', 'metric_fact', ['subject_user_id', 'occurred_at'], unique=False)
    op.create_index('uq_metric_fact_external', 'metric_fact', ['organization_id', 'metric_definition_id', 'external_id'], unique=True, postgresql_where='external_id IS NOT NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_metric_fact_external', table_name='metric_fact', postgresql_where='external_id IS NOT NULL')
    op.drop_index('ix_metric_fact_subject_time', table_name='metric_fact')
    op.drop_index('ix_metric_fact_leaderboard', table_name='metric_fact')
    op.drop_table('metric_fact')
    # ### end Alembic commands ###
