"""rule media is a fallback

Flips the precedence between a rule's media and a person's walk-up music.

It used to be that a rule with media overrode everybody's. That is backwards
for the common case: most people never open their settings, so a rule's clip is
best understood as the **fallback** everybody gets, with the people who have
chosen their own keeping theirs.

`allow_personal_media` off restores the old behaviour per rule, for the win
that should always sound the same. Off with no media is a deliberate silence —
the announcement still appears on the screen, it just plays nothing.

Revision ID: 3436beb94a7e
Revises: 991102e576a5
Create Date: 2026-08-17 18:11:59.938010
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '3436beb94a7e'
down_revision: str | None = '991102e576a5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Nullable, defaulted, tightened — existing rules have no value for it.
    op.add_column(
        'achievement_rule',
        sa.Column('allow_personal_media', sa.Boolean(), nullable=True),
    )
    # True for what already exists, which *changes their behaviour*: media on
    # an existing rule used to beat the person's own, and now yields to it.
    # That is the point of the change and is safe here — no rule in any
    # deployment has media set yet.
    op.execute("UPDATE achievement_rule SET allow_personal_media = true")
    op.alter_column('achievement_rule', 'allow_personal_media', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('achievement_rule', 'allow_personal_media')
    # ### end Alembic commands ###
