"""add user team_id

Revision ID: 7c2b73532560
Revises: d3987fbd69f1
Create Date: 2026-08-13 19:10:21.793642
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '7c2b73532560'
down_revision: str | None = 'd3987fbd69f1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('team_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_user_account_team_id'), 'user_account', ['team_id'], unique=False)
    op.create_foreign_key(op.f('fk_user_account_team_id_team'), 'user_account', 'team', ['team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_user_account_team_id_team'), 'user_account', type_='foreignkey')
    op.drop_index(op.f('ix_user_account_team_id'), table_name='user_account')
    op.drop_column('user_account', 'team_id')
    # ### end Alembic commands ###
