"""add goal recurrence

Revision ID: 94dbf79bfd70
Revises: b007e941801f
Create Date: 2026-08-13 23:07:37.876031
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '94dbf79bfd70'
down_revision: str | None = 'b007e941801f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('recurring', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('goal', sa.Column('recurrence_ends_on', sa.Date(), nullable=True))
    op.add_column('goal', sa.Column('spawned_from_goal_id', sa.BigInteger(), nullable=True))
    op.create_index('uq_goal_spawn', 'goal', ['spawned_from_goal_id', 'period_anchor'], unique=True, postgresql_where='spawned_from_goal_id IS NOT NULL')
    op.create_foreign_key(op.f('fk_goal_spawned_from_goal_id_goal'), 'goal', 'goal', ['spawned_from_goal_id'], ['id'], ondelete='CASCADE')
    op.create_check_constraint(op.f('ck_goal_recurring_shape_valid'), 'goal', "recurring = false OR (period_type <> 'custom' AND spawned_from_goal_id IS NULL)")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_goal_recurring_shape_valid'), 'goal', type_='check')
    op.drop_constraint(op.f('fk_goal_spawned_from_goal_id_goal'), 'goal', type_='foreignkey')
    op.drop_index('uq_goal_spawn', table_name='goal', postgresql_where='spawned_from_goal_id IS NOT NULL')
    op.drop_column('goal', 'spawned_from_goal_id')
    op.drop_column('goal', 'recurrence_ends_on')
    op.drop_column('goal', 'recurring')
    # ### end Alembic commands ###
