"""add allow_local_login

Revision ID: 09c657d2b926
Revises: 26c2c84a32ab
Create Date: 2026-08-13 18:25:33.885703
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '09c657d2b926'
down_revision: str | None = '26c2c84a32ab'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('allow_local_login', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_account', 'allow_local_login')
    # ### end Alembic commands ###
