"""snapshot office on metric fact

Revision ID: 75bd14e616e7
Revises: 03e6d763bb91
Create Date: 2026-08-14 16:06:50.513184
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '75bd14e616e7'
down_revision: str | None = '03e6d763bb91'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metric_fact', sa.Column('subject_office_id', sa.BigInteger(), nullable=True))
    op.create_index('ix_metric_fact_office_time', 'metric_fact', ['subject_office_id', 'occurred_at'], unique=False)

    # Backfill from each fact's team.
    #
    # The best available answer, and not a perfect one: it uses the office each
    # team belongs to *now*, because nothing recorded where they were then. Any
    # team that has already moved office has its history attributed to the new
    # one. From here on the value is snapshotted at write time and stops
    # drifting — which is the whole point of adding the column.
    op.execute(
        """
        UPDATE metric_fact AS f
        SET subject_office_id = t.office_id
        FROM team AS t
        WHERE f.subject_team_id = t.id
          AND f.subject_office_id IS NULL
        """
    )
    op.create_foreign_key(op.f('fk_metric_fact_subject_office_id_office'), 'metric_fact', 'office', ['subject_office_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_metric_fact_subject_office_id_office'), 'metric_fact', type_='foreignkey')
    op.drop_index('ix_metric_fact_office_time', table_name='metric_fact')
    op.drop_column('metric_fact', 'subject_office_id')
    # ### end Alembic commands ###
