"""achievement rule

Revision ID: 3a46c9c1c8aa
Revises: 679f930d3232
Create Date: 2026-08-14 22:32:27.825984
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '3a46c9c1c8aa'
down_revision: str | None = '679f930d3232'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievement_rule',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('metric_definition_id', sa.BigInteger(), nullable=False),
    sa.Column('comparator', sa.String(length=8), nullable=False),
    sa.Column('threshold', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('scope_team_id', sa.BigInteger(), nullable=True),
    sa.Column('media_url', sa.String(length=500), nullable=True),
    sa.Column('media_start_seconds', sa.Integer(), nullable=True),
    sa.Column('media_end_seconds', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_fact_id', sa.BigInteger(), nullable=False),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(scope = 'team' AND scope_team_id IS NOT NULL) OR (scope = 'everyone' AND scope_team_id IS NULL)", name=op.f('ck_achievement_rule_scope_matches_team')),
    sa.CheckConstraint("comparator IN ('gte', 'lte')", name=op.f('ck_achievement_rule_comparator_valid')),
    sa.CheckConstraint("scope IN ('everyone', 'team')", name=op.f('ck_achievement_rule_scope_valid')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user_account.id'], name=op.f('fk_achievement_rule_created_by_user_id_user_account'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['metric_definition_id'], ['metric_definition.id'], name=op.f('fk_achievement_rule_metric_definition_id_metric_definition'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_achievement_rule_organization_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scope_team_id'], ['team.id'], name=op.f('fk_achievement_rule_scope_team_id_team'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_achievement_rule'))
    )
    op.create_index('ix_achievement_rule_org', 'achievement_rule', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_achievement_rule_org', table_name='achievement_rule')
    op.drop_table('achievement_rule')
    # ### end Alembic commands ###
