"""add goal

Revision ID: b007e941801f
Revises: 53e2024a12fb
Create Date: 2026-08-13 22:20:13.179843
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'b007e941801f'
down_revision: str | None = '53e2024a12fb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goal',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('metric_definition_id', sa.BigInteger(), nullable=False),
    sa.Column('subject_type', sa.String(length=8), nullable=False),
    sa.Column('subject_user_id', sa.BigInteger(), nullable=True),
    sa.Column('subject_team_id', sa.BigInteger(), nullable=True),
    sa.Column('target_value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('period_type', sa.String(length=16), nullable=False),
    sa.Column('period_anchor', sa.Date(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(period_type = 'custom' AND period_start IS NOT NULL AND period_end IS NOT NULL AND period_end >= period_start) OR (period_type <> 'custom' AND period_anchor IS NOT NULL)", name=op.f('ck_goal_period_fields_match_type')),
    sa.CheckConstraint("(subject_type = 'user' AND subject_user_id IS NOT NULL AND subject_team_id IS NULL) OR (subject_type = 'team' AND subject_team_id IS NOT NULL AND subject_user_id IS NULL)", name=op.f('ck_goal_subject_matches_type')),
    sa.CheckConstraint("period_type IN ('day', 'week', 'month', 'quarter', 'year', 'custom')", name=op.f('ck_goal_period_type_valid')),
    sa.CheckConstraint("subject_type IN ('user', 'team')", name=op.f('ck_goal_subject_type_valid')),
    sa.CheckConstraint('target_value > 0', name=op.f('ck_goal_target_positive')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user_account.id'], name=op.f('fk_goal_created_by_user_id_user_account'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['metric_definition_id'], ['metric_definition.id'], name=op.f('fk_goal_metric_definition_id_metric_definition')),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_goal_organization_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_team_id'], ['team.id'], name=op.f('fk_goal_subject_team_id_team'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_user_id'], ['user_account.id'], name=op.f('fk_goal_subject_user_id_user_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goal'))
    )
    op.create_index('ix_goal_org_period', 'goal', ['organization_id', 'period_anchor'], unique=False)
    op.create_index('ix_goal_subject_team', 'goal', ['subject_team_id'], unique=False)
    op.create_index('ix_goal_subject_user', 'goal', ['subject_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_goal_subject_user', table_name='goal')
    op.drop_index('ix_goal_subject_team', table_name='goal')
    op.drop_index('ix_goal_org_period', table_name='goal')
    op.drop_table('goal')
    # ### end Alembic commands ###
