"""create organization and user_account

Revision ID: d90a21c629e4
Revises: 
Create Date: 2026-08-12 22:46:31.078209
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'd90a21c629e4'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('timezone', sa.String(length=64), server_default='UTC', nullable=False),
    sa.Column('week_starts_on', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('fiscal_year_start_month', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='USD', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('fiscal_year_start_month BETWEEN 1 AND 12', name=op.f('ck_organization_fiscal_year_start_month_range')),
    sa.CheckConstraint('week_starts_on BETWEEN 0 AND 6', name=op.f('ck_organization_week_starts_on_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization'))
    )
    op.create_table('user_account',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('org_role', sa.String(length=20), server_default='agent', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='invited', nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('external_subject_id', sa.String(length=255), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("org_role IN ('admin', 'manager', 'agent', 'viewer')", name=op.f('ck_user_account_org_role_valid')),
    sa.CheckConstraint("status IN ('invited', 'active', 'suspended')", name=op.f('ck_user_account_status_valid')),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_user_account_organization_id_organization')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_account'))
    )
    op.create_index(op.f('ix_user_account_external_subject_id'), 'user_account', ['external_subject_id'], unique=False)
    op.create_index(op.f('ix_user_account_organization_id'), 'user_account', ['organization_id'], unique=False)
    op.create_index('uq_user_account_org_email_lower', 'user_account', ['organization_id', sa.literal_column('lower(email)')], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_user_account_org_email_lower', table_name='user_account')
    op.drop_index(op.f('ix_user_account_organization_id'), table_name='user_account')
    op.drop_index(op.f('ix_user_account_external_subject_id'), table_name='user_account')
    op.drop_table('user_account')
    op.drop_table('organization')
    # ### end Alembic commands ###
