"""add metric_definition

Revision ID: 05c9b30d5444
Revises: d7abd64d8a2c
Create Date: 2026-08-13 20:41:52.698940
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '05c9b30d5444'
down_revision: str | None = 'd7abd64d8a2c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metric_definition',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('aggregation', sa.String(length=16), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('decimal_places', sa.Integer(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("aggregation IN ('sum', 'count', 'avg', 'max', 'min', 'last')", name=op.f('ck_metric_definition_aggregation_valid')),
    sa.CheckConstraint("direction IN ('higher_is_better', 'lower_is_better')", name=op.f('ck_metric_definition_direction_valid')),
    sa.CheckConstraint("unit IN ('count', 'currency', 'percent', 'duration')", name=op.f('ck_metric_definition_unit_valid')),
    sa.CheckConstraint('decimal_places BETWEEN 0 AND 4', name=op.f('ck_metric_definition_decimal_places_valid')),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_metric_definition_organization_id_organization'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metric_definition')),
    sa.UniqueConstraint('organization_id', 'key', name='uq_metric_definition_org_key')
    )
    op.create_index(op.f('ix_metric_definition_organization_id'), 'metric_definition', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metric_definition_organization_id'), table_name='metric_definition')
    op.drop_table('metric_definition')
    # ### end Alembic commands ###
