"""create user_token

Revision ID: 28372539be06
Revises: 1222503d9665
Create Date: 2026-08-13 18:53:04.581429
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '28372539be06'
down_revision: str | None = '1222503d9665'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_token',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("purpose IN ('invite', 'password_reset')", name=op.f('ck_user_token_purpose_valid')),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_user_token_user_id_user_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_token'))
    )
    op.create_index(op.f('ix_user_token_expires_at'), 'user_token', ['expires_at'], unique=False)
    op.create_index(op.f('ix_user_token_token_hash'), 'user_token', ['token_hash'], unique=True)
    op.create_index(op.f('ix_user_token_user_id'), 'user_token', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_token_user_id'), table_name='user_token')
    op.drop_index(op.f('ix_user_token_token_hash'), table_name='user_token')
    op.drop_index(op.f('ix_user_token_expires_at'), table_name='user_token')
    op.drop_table('user_token')
    # ### end Alembic commands ###
