"""Authored channels, replacing the office-derived ones.

Through Phase 1 a display pointed at an office and played every TV-enabled,
org-visible board that matched it, ordered by name. Nobody chose the running
order and a board was the only thing a wall could show.

**This migration must seed, not reset.** Every wall currently showing something
has to keep showing exactly the same thing in the same order afterwards — an
upgrade that blanks every screen in a building is not an upgrade. So it builds
each office's channel from precisely the query the feed used to run, and points
the existing displays at it.

Written by hand rather than autogenerated. Autogenerate would produce the two
tables and then happily drop `display.office_id`, taking every wall's contents
with it.

Revision ID: b7e21d4a9c33
Revises: 3a46c9c1c8aa
"""

import sqlalchemy as sa
from alembic import op

revision = "b7e21d4a9c33"
down_revision = "3a46c9c1c8aa"
branch_labels = None
depends_on = None

#: Matches `channel.DEFAULT_DWELL_SECONDS`. Duplicated here because a migration
#: has to keep working after the constant moves or changes.
DWELL = 20


def upgrade() -> None:
    op.create_table(
        "channel",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("organization_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organization.id"], name=op.f("fk_channel_organization_id_organization"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_channel")),
    )
    op.create_index(op.f("ix_channel_organization_id"), "channel", ["organization_id"])

    op.create_table(
        "channel_screen",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("channel_id", sa.BigInteger(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("dwell_seconds", sa.Integer(), nullable=False),
        sa.Column("leaderboard_id", sa.BigInteger(), nullable=True),
        sa.Column("goal_id", sa.BigInteger(), nullable=True),
        sa.Column("url", sa.String(length=500), nullable=True),
        sa.Column("title", sa.String(length=120), nullable=True),
        sa.Column("body", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "kind IN ('leaderboard', 'goal', 'achievements', 'image', 'video', 'message')",
            name=op.f("ck_channel_screen_kind_valid"),
        ),
        sa.CheckConstraint(
            "(kind = 'leaderboard' AND leaderboard_id IS NOT NULL) OR "
            "(kind = 'goal' AND goal_id IS NOT NULL) OR "
            "(kind = 'achievements') OR "
            "(kind IN ('image', 'video') AND url IS NOT NULL) OR "
            "(kind = 'message' AND title IS NOT NULL)",
            name=op.f("ck_channel_screen_payload_matches_kind"),
        ),
        sa.CheckConstraint("dwell_seconds BETWEEN 5 AND 300", name=op.f("ck_channel_screen_dwell_sane")),
        sa.ForeignKeyConstraint(["channel_id"], ["channel.id"], name=op.f("fk_channel_screen_channel_id_channel"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["leaderboard_id"], ["leaderboard.id"], name=op.f("fk_channel_screen_leaderboard_id_leaderboard"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["goal_id"], ["goal.id"], name=op.f("fk_channel_screen_goal_id_goal"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_channel_screen")),
    )
    op.create_index("ix_channel_screen_order", "channel_screen", ["channel_id", "position"])

    # ── Seed one channel per office, plus one org-wide ───────────────────────
    #
    # Every office gets one whether or not it has a display today, so an admin
    # adding a screen tomorrow has somewhere to point it. The organization-wide
    # channel is what a reception display used, where `office_id` was NULL.
    op.execute(
        """
        INSERT INTO channel (organization_id, name)
        SELECT o.organization_id, o.name FROM office o
        UNION ALL
        SELECT org.id, 'Whole organization' FROM organization org
        """
    )

    # ── Fill them from exactly the query the feed used to run ────────────────
    #
    # `is_tv_enabled AND visibility = 'org'`, narrowed to organization-wide
    # boards plus this office's, ordered by name. Reproduced rather than
    # approximated: anything else and a wall comes back different on Monday.
    op.execute(
        """
        INSERT INTO channel_screen (channel_id, position, kind, dwell_seconds, leaderboard_id)
        SELECT c.id,
               row_number() OVER (PARTITION BY c.id ORDER BY l.name) - 1,
               'leaderboard',
               %(dwell)s,
               l.id
          FROM channel c
          JOIN office o
            ON o.organization_id = c.organization_id AND o.name = c.name
          JOIN leaderboard l
            ON l.organization_id = c.organization_id
           AND l.archived_at IS NULL
           AND l.is_tv_enabled
           AND l.visibility = 'org'
           AND (l.scope_type = 'organization' OR l.scope_office_id = o.id)
        """
        % {"dwell": DWELL}
    )
    # The organization-wide channel saw no office filter at all.
    op.execute(
        """
        INSERT INTO channel_screen (channel_id, position, kind, dwell_seconds, leaderboard_id)
        SELECT c.id,
               row_number() OVER (PARTITION BY c.id ORDER BY l.name) - 1,
               'leaderboard',
               %(dwell)s,
               l.id
          FROM channel c
          JOIN leaderboard l
            ON l.organization_id = c.organization_id
           AND l.archived_at IS NULL
           AND l.is_tv_enabled
           AND l.visibility = 'org'
         WHERE c.name = 'Whole organization'
        """
        % {"dwell": DWELL}
    )

    # ── Point the displays at their channel ──────────────────────────────────
    op.add_column("display", sa.Column("channel_id", sa.BigInteger(), nullable=True))
    op.execute(
        """
        UPDATE display d
           SET channel_id = c.id
          FROM channel c
          JOIN office o
            ON o.organization_id = c.organization_id AND o.name = c.name
         WHERE d.office_id = o.id
        """
    )
    op.execute(
        """
        UPDATE display d
           SET channel_id = c.id
          FROM channel c
         WHERE d.office_id IS NULL
           AND c.organization_id = d.organization_id
           AND c.name = 'Whole organization'
        """
    )

    op.alter_column("display", "channel_id", nullable=False)
    op.create_index(op.f("ix_display_channel_id"), "display", ["channel_id"])
    op.create_foreign_key(
        op.f("fk_display_channel_id_channel"), "display", "channel",
        ["channel_id"], ["id"], ondelete="CASCADE",
    )
    op.drop_column("display", "office_id")


def downgrade() -> None:
    """Back to office-derived channels.

    Lossy, and unavoidably so: an authored order, a message screen or a video
    has no office to be derived from, and there is nowhere to put them. A
    channel whose name matches an office resolves back to it; anything else
    becomes a reception display showing everything.
    """
    op.add_column("display", sa.Column("office_id", sa.BigInteger(), nullable=True))
    op.execute(
        """
        UPDATE display d
           SET office_id = o.id
          FROM channel c
          JOIN office o
            ON o.organization_id = c.organization_id AND o.name = c.name
         WHERE d.channel_id = c.id
        """
    )
    op.create_foreign_key(
        op.f("fk_display_office_id_office"), "display", "office",
        ["office_id"], ["id"], ondelete="CASCADE",
    )

    op.drop_constraint(op.f("fk_display_channel_id_channel"), "display", type_="foreignkey")
    op.drop_index(op.f("ix_display_channel_id"), table_name="display")
    op.drop_column("display", "channel_id")

    op.drop_index("ix_channel_screen_order", table_name="channel_screen")
    op.drop_table("channel_screen")
    op.drop_index(op.f("ix_channel_organization_id"), table_name="channel")
    op.drop_table("channel")
