"""drop allow_local_login

Revision ID: 3ded52b03945
Revises: 09c657d2b926
Create Date: 2026-08-13 18:31:26.148126
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '3ded52b03945'
down_revision: str | None = '09c657d2b926'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_account', 'allow_local_login')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('allow_local_login', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
