"""channel audience

Two things, both about keeping one office's numbers off another office's wall.

**`channel.scope_*`** is the audience. Every screen inherits it, so a wall is
right by default and spillover is something somebody chose rather than
something they forgot. `channel_screen.scope_*` is the per-screen override,
NULL for almost every row — it exists for the company-wide board on a floor
that otherwise shows only itself.

**`notification.about_team_id` / `about_office_id`** snapshot where the
achiever sat when they earned it, so a recent-wins panel can be filtered.
Backfilled below from current membership, which is the best available answer
for rows written before the columns existed and is wrong only for anybody who
has since transferred — a one-off inaccuracy in old history, against getting it
right from here on.

Revision ID: c8860eaaa3c9
Revises: b7e21d4a9c33
Create Date: 2026-08-17 16:18:06.868982
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'c8860eaaa3c9'
down_revision: str | None = 'b7e21d4a9c33'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Nullable, backfilled, then tightened — the standard three steps for a
    # NOT NULL column on a table that already has rows.
    op.add_column('channel', sa.Column('scope_type', sa.String(length=16), nullable=True))
    op.add_column('channel', sa.Column('scope_office_id', sa.BigInteger(), nullable=True))
    op.add_column('channel', sa.Column('scope_team_id', sa.BigInteger(), nullable=True))

    # Every existing channel came from an office (or is the organization-wide
    # one), because that is how the previous migration seeded them. Matching
    # the name back to the office means an upgrade *delivers* the separation
    # rather than leaving every wall wide open until somebody sets it.
    op.execute("UPDATE channel SET scope_type = 'organization'")
    op.execute(
        """
        UPDATE channel c
           SET scope_type = 'office',
               scope_office_id = o.id
          FROM office o
         WHERE o.organization_id = c.organization_id
           AND o.name = c.name
        """
    )
    op.alter_column('channel', 'scope_type', nullable=False)

    op.create_foreign_key(op.f('fk_channel_scope_team_id_team'), 'channel', 'team', ['scope_team_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_channel_scope_office_id_office'), 'channel', 'office', ['scope_office_id'], ['id'], ondelete='CASCADE')
    op.create_check_constraint(op.f('ck_channel_scope_matches_type'), 'channel', "(scope_type = 'organization' AND scope_office_id IS NULL AND scope_team_id IS NULL) OR (scope_type = 'office' AND scope_office_id IS NOT NULL AND scope_team_id IS NULL) OR (scope_type = 'team' AND scope_team_id IS NOT NULL AND scope_office_id IS NULL)")
    op.create_check_constraint(op.f('ck_channel_scope_valid'), 'channel', "scope_type IN ('organization', 'office', 'team')")
    op.add_column('channel_screen', sa.Column('scope_type', sa.String(length=16), nullable=True))
    op.add_column('channel_screen', sa.Column('scope_office_id', sa.BigInteger(), nullable=True))
    op.add_column('channel_screen', sa.Column('scope_team_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(op.f('fk_channel_screen_scope_office_id_office'), 'channel_screen', 'office', ['scope_office_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_channel_screen_scope_team_id_team'), 'channel_screen', 'team', ['scope_team_id'], ['id'], ondelete='CASCADE')
    op.create_check_constraint(op.f('ck_channel_screen_override_matches_type'), 'channel_screen', "scope_type IS NULL OR (scope_type = 'organization' AND scope_office_id IS NULL AND scope_team_id IS NULL) OR (scope_type = 'office' AND scope_office_id IS NOT NULL) OR (scope_type = 'team' AND scope_team_id IS NOT NULL)")
    op.add_column('notification', sa.Column('about_team_id', sa.BigInteger(), nullable=True))
    op.add_column('notification', sa.Column('about_office_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(op.f('fk_notification_about_team_id_team'), 'notification', 'team', ['about_team_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_notification_about_office_id_office'), 'notification', 'office', ['about_office_id'], ['id'], ondelete='SET NULL')
    # Backfill from current membership. Not perfect for somebody who has
    # already moved, and there is nothing better to use — the snapshot only
    # starts being exact for achievements earned from now on.
    op.execute(
        """
        UPDATE notification n
           SET about_team_id = u.team_id,
               about_office_id = t.office_id
          FROM user_account u
          LEFT JOIN team t ON t.id = u.team_id
         WHERE n.about_user_id = u.id
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_notification_about_office_id_office'), 'notification', type_='foreignkey')
    op.drop_constraint(op.f('fk_notification_about_team_id_team'), 'notification', type_='foreignkey')
    op.drop_column('notification', 'about_office_id')
    op.drop_column('notification', 'about_team_id')
    op.drop_constraint(op.f('ck_channel_screen_override_matches_type'), 'channel_screen', type_='check')
    op.drop_constraint(op.f('fk_channel_screen_scope_team_id_team'), 'channel_screen', type_='foreignkey')
    op.drop_constraint(op.f('fk_channel_screen_scope_office_id_office'), 'channel_screen', type_='foreignkey')
    op.drop_column('channel_screen', 'scope_team_id')
    op.drop_column('channel_screen', 'scope_office_id')
    op.drop_column('channel_screen', 'scope_type')
    op.drop_constraint(op.f('ck_channel_scope_valid'), 'channel', type_='check')
    op.drop_constraint(op.f('ck_channel_scope_matches_type'), 'channel', type_='check')
    op.drop_constraint(op.f('fk_channel_scope_office_id_office'), 'channel', type_='foreignkey')
    op.drop_constraint(op.f('fk_channel_scope_team_id_team'), 'channel', type_='foreignkey')
    op.drop_column('channel', 'scope_team_id')
    op.drop_column('channel', 'scope_office_id')
    op.drop_column('channel', 'scope_type')
    # ### end Alembic commands ###
