"""directory sync tables

Two tables so that **sync never writes to `user_account` directly**.

Everything a directory reports lands in `directory_person` with a status, and only
an approved row becomes a real account. Same shape as the quarantine for unmatched
metric rows, and the same reason: an automated guess about identity should be
answerable before it becomes a fact.

`directory_rule` holds the "people like this become that" statements. **No position
column, deliberately** — which rule wins is decided by specificity, precisely so an
admin adding a broad rule cannot silently disable every specific one. A column for
order would invite somebody to make order matter later.

Nothing to backfill: both tables start empty, and a deployment that never connects a
directory keeps them empty for ever.

Revision ID: 168be4df27a4
Revises: a1c4f7b90e32
Create Date: 2026-08-26 21:42:48.352402
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '168be4df27a4'
down_revision: str | None = 'a1c4f7b90e32'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('directory_rule',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('department', sa.String(length=200), nullable=False),
    sa.Column('job_title', sa.String(length=200), nullable=False),
    sa.Column('office', sa.String(length=200), nullable=False),
    sa.Column('group', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_directory_rule_organization_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name=op.f('fk_directory_rule_team_id_team'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_directory_rule'))
    )
    op.create_index('ix_directory_rule_org', 'directory_rule', ['organization_id'], unique=False)
    op.create_table('directory_person',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('job_title', sa.String(length=200), nullable=False),
    sa.Column('department', sa.String(length=200), nullable=False),
    sa.Column('office_location', sa.String(length=200), nullable=False),
    sa.Column('groups', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('user_account_id', sa.BigInteger(), nullable=True),
    sa.Column('pending_reason', sa.String(length=200), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_directory_person_organization_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_account_id'], ['user_account.id'], name=op.f('fk_directory_person_user_account_id_user_account'), ondelete='SET NULL'),
    sa.CheckConstraint("status IN ('pending', 'approved', 'declined', 'archived')", name=op.f('ck_directory_person_directory_status_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_directory_person')),
    sa.UniqueConstraint('organization_id', 'provider', 'external_id', name='uq_directory_person_external')
    )
    op.create_index('ix_directory_person_status', 'directory_person', ['organization_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_directory_person_status', table_name='directory_person')
    op.drop_table('directory_person')
    op.drop_index('ix_directory_rule_org', table_name='directory_rule')
    op.drop_table('directory_rule')
    # ### end Alembic commands ###
