"""walkup media table

Revision ID: 679f930d3232
Revises: c9f8a2dca00a
Create Date: 2026-08-14 22:09:28.303206
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '679f930d3232'
down_revision: str | None = 'c9f8a2dca00a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('walkup_media',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('start_seconds', sa.Integer(), nullable=False),
    sa.Column('end_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_walkup_media_user_id_user_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_walkup_media'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('walkup_media')
    # ### end Alembic commands ###
