"""create team

Revision ID: 1222503d9665
Revises: 3ded52b03945
Create Date: 2026-08-13 18:43:02.673636
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '1222503d9665'
down_revision: str | None = '3ded52b03945'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('parent_team_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_team_organization_id_organization')),
    sa.ForeignKeyConstraint(['parent_team_id'], ['team.id'], name=op.f('fk_team_parent_team_id_team')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team'))
    )
    op.create_index(op.f('ix_team_organization_id'), 'team', ['organization_id'], unique=False)
    op.create_index(op.f('ix_team_parent_team_id'), 'team', ['parent_team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_parent_team_id'), table_name='team')
    op.drop_index(op.f('ix_team_organization_id'), table_name='team')
    op.drop_table('team')
    # ### end Alembic commands ###
