"""flag corrected metric facts

Revision ID: 53e2024a12fb
Revises: e5f0d64f428c
Create Date: 2026-08-13 21:37:23.039545
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '53e2024a12fb'
down_revision: str | None = 'e5f0d64f428c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metric_fact', sa.Column('corrected_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('metric_fact', sa.Column('corrected_by_user_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(op.f('fk_metric_fact_corrected_by_user_id_user_account'), 'metric_fact', 'user_account', ['corrected_by_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_metric_fact_corrected_by_user_id_user_account'), 'metric_fact', type_='foreignkey')
    op.drop_column('metric_fact', 'corrected_by_user_id')
    op.drop_column('metric_fact', 'corrected_at')
    # ### end Alembic commands ###
