"""directory runs and the sync switch

Revision ID: 13adc7eed7fa
Revises: 168be4df27a4
Create Date: 2026-08-26 23:22:58.071538
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '13adc7eed7fa'
down_revision: str | None = '168be4df27a4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('directory_run',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('trigger', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('people_seen', sa.Integer(), nullable=False),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('archived', sa.Integer(), nullable=False),
    sa.Column('needs_review', sa.Integer(), nullable=False),
    sa.Column('pending', sa.Integer(), nullable=False),
    sa.Column('applied', sa.Integer(), nullable=False),
    sa.Column('error', sa.String(length=2000), nullable=True),
    sa.CheckConstraint("status IN ('running', 'ok', 'partial', 'failed')", name=op.f('ck_directory_run_directory_run_status_valid')),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_directory_run_organization_id_organization'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_directory_run'))
    )
    op.create_index('ix_directory_run_recent', 'directory_run', ['organization_id', 'started_at'], unique=False)
    op.add_column('oauth_client', sa.Column('directory_sync_enabled', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oauth_client', 'directory_sync_enabled')
    op.drop_index('ix_directory_run_recent', table_name='directory_run')
    op.drop_table('directory_run')
    # ### end Alembic commands ###
