"""flatten teams: drop parent_team_id

Revision ID: d3987fbd69f1
Revises: 28372539be06
Create Date: 2026-08-13 19:03:29.530938
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'd3987fbd69f1'
down_revision: str | None = '28372539be06'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_parent_team_id'), table_name='team')
    op.drop_constraint(op.f('fk_team_parent_team_id_team'), 'team', type_='foreignkey')
    op.drop_column('team', 'parent_team_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('parent_team_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_team_parent_team_id_team'), 'team', 'team', ['parent_team_id'], ['id'])
    op.create_index(op.f('ix_team_parent_team_id'), 'team', ['parent_team_id'], unique=False)
    # ### end Alembic commands ###
