"""leaderboard office scope

Revision ID: 1129f4fbdc82
Revises: 75bd14e616e7
Create Date: 2026-08-14 16:11:50.330604
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '1129f4fbdc82'
down_revision: str | None = '75bd14e616e7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leaderboard', sa.Column('scope_office_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(op.f('fk_leaderboard_scope_office_id_office'), 'leaderboard', 'office', ['scope_office_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###

    # Hand-written from here. Autogenerate detects an ADDED check constraint but
    # not a CHANGED one, so both of these were left at their old definitions and
    # rejected every `office` row — the same trap that bit the `viewer` role
    # removal in 1b. `op.f()` is required, or the naming convention prefixes an
    # already-complete name a second time.
    op.drop_constraint(op.f("ck_leaderboard_entity_type_valid"), "leaderboard", type_="check")
    op.create_check_constraint(
        op.f("ck_leaderboard_entity_type_valid"),
        "leaderboard",
        "entity_type IN ('user', 'team', 'office')",
    )

    op.drop_constraint(op.f("ck_leaderboard_scope_type_valid"), "leaderboard", type_="check")
    op.create_check_constraint(
        op.f("ck_leaderboard_scope_type_valid"),
        "leaderboard",
        "scope_type IN ('organization', 'team', 'office')",
    )

    op.drop_constraint(op.f("ck_leaderboard_scope_matches_type"), "leaderboard", type_="check")
    op.create_check_constraint(
        op.f("ck_leaderboard_scope_matches_type"),
        "leaderboard",
        "(scope_type = 'organization' AND scope_team_id IS NULL "
        "AND scope_office_id IS NULL) OR "
        "(scope_type = 'team' AND scope_team_id IS NOT NULL "
        "AND scope_office_id IS NULL) OR "
        "(scope_type = 'office' AND scope_office_id IS NOT NULL "
        "AND scope_team_id IS NULL)",
    )


def downgrade() -> None:
    # Narrowing again would fail on any office row, so they go first.
    op.execute("DELETE FROM leaderboard WHERE scope_type = 'office' OR entity_type = 'office'")
    for name, table, condition in (
        ("ck_leaderboard_entity_type_valid", "leaderboard", "entity_type IN ('user', 'team')"),
        ("ck_leaderboard_scope_type_valid", "leaderboard", "scope_type IN ('organization', 'team')"),
        (
            "ck_leaderboard_scope_matches_type",
            "leaderboard",
            "(scope_type = 'team' AND scope_team_id IS NOT NULL) OR "
            "(scope_type = 'organization' AND scope_team_id IS NULL)",
        ),
    ):
        op.drop_constraint(op.f(name), table, type_="check")
        op.create_check_constraint(op.f(name), table, condition)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_leaderboard_scope_office_id_office'), 'leaderboard', type_='foreignkey')
    op.drop_column('leaderboard', 'scope_office_id')
    # ### end Alembic commands ###
