"""integrations: sources, mappings, identities, sync runs

The Phase 3 foundation. Five new tables, and one change to `metric_fact` that is
the reason this migration matters more than the table count suggests.

**`uq_metric_fact_external` gains `data_source_id`.** That index is what makes a
sync idempotent — re-reading yesterday's deals writes nothing new because the
source's own row ids are already present. Without the source in the key, two
connectors issuing the same id would collide: a Salesforce opportunity and a
spreadsheet row are both plausibly "1042", and the second connector would silently
update the first connector's rows instead of adding its own.

`metric_fact.data_source_id` is `ON DELETE RESTRICT`, not CASCADE or SET NULL.
Deleting a source must not delete the measurements it collected — leaderboards and
settled competitions were computed from them — and nulling the column would break
the key above, so re-connecting the same source would import everything twice. A
source that has written facts is disabled, not deleted, the same rule as a metric
that has been measured.

Existing rows get `data_source_id = NULL`, which is correct: everything in the
table so far was either seeded or typed by a person, and the partial index only
covers rows that have an external id.


Revision ID: dff922ed0d33
Revises: 0cdc5b353384
Create Date: 2026-08-19 17:48:49.757384
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'dff922ed0d33'
down_revision: str | None = '0cdc5b353384'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_source',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('connector', sa.String(length=40), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('interval_minutes', sa.Integer(), server_default='60', nullable=False),
    sa.Column('backfill_days', sa.Integer(), server_default='90', nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status', sa.String(length=16), nullable=True),
    sa.Column('failure_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("last_status IS NULL OR last_status IN ('ok', 'partial', 'failed')", name=op.f('ck_data_source_last_status_valid')),
    sa.CheckConstraint('backfill_days BETWEEN 0 AND 3650', name=op.f('ck_data_source_backfill_sane')),
    sa.CheckConstraint('interval_minutes >= 5', name=op.f('ck_data_source_interval_sane')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user_account.id'], name=op.f('fk_data_source_created_by_user_id_user_account'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_data_source_organization_id_organization'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_source'))
    )
    op.create_index('ix_data_source_due', 'data_source', ['enabled', 'next_run_at'], unique=False)
    op.create_index('ix_data_source_org', 'data_source', ['organization_id'], unique=False)
    op.create_table('connector_credential',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('data_source_id', sa.BigInteger(), nullable=False),
    sa.Column('secrets_encrypted', sa.String(length=8000), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_source.id'], name=op.f('fk_connector_credential_data_source_id_data_source'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_connector_credential'))
    )
    op.create_index('uq_connector_credential_source', 'connector_credential', ['data_source_id'], unique=True)
    op.create_table('source_mapping',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('data_source_id', sa.BigInteger(), nullable=False),
    sa.Column('metric_definition_id', sa.BigInteger(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('value_field', sa.String(length=200), nullable=True),
    sa.Column('occurred_at_field', sa.String(length=200), nullable=False),
    sa.Column('subject_field', sa.String(length=200), nullable=False),
    sa.Column('external_id_field', sa.String(length=200), nullable=True),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('multiplier', sa.Numeric(precision=12, scale=6), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('multiplier <> 0', name=op.f('ck_source_mapping_multiplier_not_zero')),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_source.id'], name=op.f('fk_source_mapping_data_source_id_data_source'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['metric_definition_id'], ['metric_definition.id'], name=op.f('fk_source_mapping_metric_definition_id_metric_definition'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_source_mapping_organization_id_organization'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_mapping'))
    )
    op.create_index('uq_source_mapping_source_metric', 'source_mapping', ['data_source_id', 'metric_definition_id'], unique=True)
    op.create_table('sync_run',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('data_source_id', sa.BigInteger(), nullable=False),
    sa.Column('trigger', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='running', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rows_read', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rows_written', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rows_quarantined', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rows_skipped', sa.Integer(), server_default='0', nullable=False),
    sa.Column('conflicts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error', sa.String(length=2000), nullable=True),
    sa.CheckConstraint("status IN ('running', 'ok', 'partial', 'failed')", name=op.f('ck_sync_run_status_valid')),
    sa.CheckConstraint("trigger IN ('schedule', 'manual', 'webhook')", name=op.f('ck_sync_run_trigger_valid')),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_source.id'], name=op.f('fk_sync_run_data_source_id_data_source'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_sync_run_organization_id_organization'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_run'))
    )
    op.create_index('ix_sync_run_source_time', 'sync_run', ['data_source_id', 'started_at'], unique=False)
    op.create_table('user_identity',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('data_source_id', sa.BigInteger(), nullable=False),
    sa.Column('external_identifier', sa.String(length=320), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('ignored', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('pending_rows', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('NOT (user_id IS NOT NULL AND ignored)', name=op.f('ck_user_identity_mapped_or_ignored')),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_source.id'], name=op.f('fk_user_identity_data_source_id_data_source'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_user_identity_organization_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_user_identity_user_id_user_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_identity'))
    )
    op.create_index('ix_user_identity_org', 'user_identity', ['organization_id'], unique=False)
    op.create_index('uq_user_identity_source_external', 'user_identity', ['data_source_id', 'external_identifier'], unique=True)
    op.add_column('metric_fact', sa.Column('data_source_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(
        op.f('fk_metric_fact_data_source_id_data_source'),
        'metric_fact', 'data_source', ['data_source_id'], ['id'], ondelete='RESTRICT',
    )

    # Hand-written, replacing what autogenerate produced.
    #
    # Autogenerate emitted a plain DROP INDEX + CREATE UNIQUE INDEX. Both take an
    # exclusive lock on `metric_fact` for the whole build, and every write path in
    # the product touches that table — so on a production-sized table the deploy
    # blocks all writes until the index finishes. At 3,000 rows it is instant,
    # which is exactly why it passed review; at four million it is an outage.
    #
    # The order matters. The new index is built first, under a temporary name, so
    # uniqueness is enforced by *something* at every instant; then the old one goes
    # and the new one takes its name. A rename is a catalogue update — instant, and
    # it needs no lock worth having.
    #
    # `CONCURRENTLY` cannot run inside a transaction, hence the autocommit block —
    # the same shape as 3d61902cb44e.
    with op.get_context().autocommit_block():
        op.execute(
            """
            CREATE UNIQUE INDEX CONCURRENTLY uq_metric_fact_external_new
            ON metric_fact (organization_id, data_source_id,
                            metric_definition_id, external_id)
            NULLS NOT DISTINCT
            WHERE external_id IS NOT NULL
            """
        )
        op.execute("DROP INDEX CONCURRENTLY IF EXISTS uq_metric_fact_external")
        op.execute(
            "ALTER INDEX uq_metric_fact_external_new "
            "RENAME TO uq_metric_fact_external"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Same build-then-swap, in reverse, and concurrently for the same reason.
    with op.get_context().autocommit_block():
        op.execute(
            """
            CREATE UNIQUE INDEX CONCURRENTLY uq_metric_fact_external_old
            ON metric_fact (organization_id, metric_definition_id, external_id)
            WHERE external_id IS NOT NULL
            """
        )
        op.execute("DROP INDEX CONCURRENTLY IF EXISTS uq_metric_fact_external")
        op.execute(
            "ALTER INDEX uq_metric_fact_external_old "
            "RENAME TO uq_metric_fact_external"
        )

    op.drop_constraint(
        op.f('fk_metric_fact_data_source_id_data_source'),
        'metric_fact', type_='foreignkey',
    )
    op.drop_column('metric_fact', 'data_source_id')
    op.drop_index('uq_user_identity_source_external', table_name='user_identity')
    op.drop_index('ix_user_identity_org', table_name='user_identity')
    op.drop_table('user_identity')
    op.drop_index('ix_sync_run_source_time', table_name='sync_run')
    op.drop_table('sync_run')
    op.drop_index('uq_source_mapping_source_metric', table_name='source_mapping')
    op.drop_table('source_mapping')
    op.drop_index('uq_connector_credential_source', table_name='connector_credential')
    op.drop_table('connector_credential')
    op.drop_index('ix_data_source_org', table_name='data_source')
    op.drop_index('ix_data_source_due', table_name='data_source')
    op.drop_table('data_source')
    # ### end Alembic commands ###
