"""walkup media

Revision ID: c9f8a2dca00a
Revises: 81b04ef02dcf
Create Date: 2026-08-14 22:09:01.204074
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'c9f8a2dca00a'
down_revision: str | None = '81b04ef02dcf'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('media_url', sa.String(length=500), nullable=True))
    op.add_column('notification', sa.Column('media_start_seconds', sa.Integer(), nullable=True))
    op.add_column('notification', sa.Column('media_end_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'media_end_seconds')
    op.drop_column('notification', 'media_start_seconds')
    op.drop_column('notification', 'media_url')
    # ### end Alembic commands ###
