"""webhook event inbox

Revision ID: 8ca82511c871
Revises: dff922ed0d33
Create Date: 2026-08-19 20:28:33.863865
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '8ca82511c871'
down_revision: str | None = 'dff922ed0d33'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_event',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('data_source_id', sa.BigInteger(), nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_source.id'], name=op.f('fk_webhook_event_data_source_id_data_source'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_webhook_event_organization_id_organization'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_event'))
    )
    op.create_index('ix_webhook_event_source_time', 'webhook_event', ['data_source_id', 'received_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_webhook_event_source_time', table_name='webhook_event')
    op.drop_table('webhook_event')
    # ### end Alembic commands ###
