"""create login_attempt

Revision ID: ea979e4d0d6f
Revises: 42a342630d34
Create Date: 2026-08-13 17:44:04.028360
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'ea979e4d0d6f'
down_revision: str | None = '42a342630d34'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_attempt',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_login_attempt'))
    )
    op.create_index(op.f('ix_login_attempt_attempted_at'), 'login_attempt', ['attempted_at'], unique=False)
    op.create_index('ix_login_attempt_email_time', 'login_attempt', ['email', 'attempted_at'], unique=False)
    op.create_index('ix_login_attempt_ip_time', 'login_attempt', ['ip_address', 'attempted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_login_attempt_ip_time', table_name='login_attempt')
    op.drop_index('ix_login_attempt_email_time', table_name='login_attempt')
    op.drop_index(op.f('ix_login_attempt_attempted_at'), table_name='login_attempt')
    op.drop_table('login_attempt')
    # ### end Alembic commands ###
