"""smtp settings

Revision ID: 68bb593b349a
Revises: 13adc7eed7fa
Create Date: 2026-08-28 21:21:47.351164
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '68bb593b349a'
down_revision: str | None = '13adc7eed7fa'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('smtp_config',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('host', sa.String(length=255), server_default='', nullable=False),
    sa.Column('port', sa.Integer(), server_default='587', nullable=False),
    sa.Column('security', sa.String(length=20), server_default='starttls', nullable=False),
    sa.Column('username', sa.String(length=320), server_default='', nullable=False),
    sa.Column('password_encrypted', sa.String(length=2000), nullable=True),
    sa.Column('from_address', sa.String(length=320), server_default='', nullable=False),
    sa.Column('from_name', sa.String(length=200), server_default='GoalGetter', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("security IN ('starttls', 'ssl', 'none')", name=op.f('ck_smtp_config_smtp_security_valid')),
    sa.CheckConstraint('port > 0 AND port < 65536', name=op.f('ck_smtp_config_smtp_port_valid')),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_smtp_config_organization_id_organization'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_smtp_config')),
    sa.UniqueConstraint('organization_id', name=op.f('uq_smtp_config_organization_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('smtp_config')
    # ### end Alembic commands ###
